"use strict";
let who = [
  "The dog",
  "My grandma",
  "The mailman",
  "My bird",
  "My neighbor",
  "A random guy on the street",
  "My best friend",
  "The teacher",
  "A squirrel",
  "My little brother",
  "The plumber",
  "The cat",
  "My boss",
  "A stranger",
  "My cousin",
  "The babysitter",
  "The pizza delivery guy",
  "My goldfish",
  "The janitor",
  "The principal",
];

let action = [
  "ate",
  "peed on",
  "crushed",
  "broke",
  "spilled juice on",
  "hid",
  "lost",
  "deleted",
  "burned",
  "ripped",
  "chewed up",
  "threw away",
  "smashed",
  "erased",
  "forgot",
  "stole",
  "messed up",
  "dropped",
  "scratched",
  "sat on",
];

let what = [
  "my homework",
  "my phone",
  "the car",
  "the computer",
  "my shoes",
  "the TV remote",
  "my backpack",
  "the project",
  "my report",
  "the tablet",
  "my notes",
  "the Wi-Fi router",
  "the lunch I made",
  "my keys",
  "the charger",
  "the presentation slides",
  "my favorite shirt",
  "the bicycle",
  "the console",
  "my essay",
];

let when = [
  "before the class",
  "when I was sleeping",
  "while I was exercising",
  "during my lunch",
  "while I was praying",
  "this morning",
  "last night",
  "yesterday afternoon",
  "during the game",
  "when I was at school",
  "on my way here",
  "while I was showering",
  "while I was eating",
  "when I got home",
  "just before the meeting",
  "while I was doing chores",
  "during the party",
  "this afternoon",
  "when I was walking the dog",
  "while I was on the bus",
];

export { who, action, what, when };
